
Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.NodeTypes.ColumnLayouts: true
    userInterface:
      translation:
        autoInclude:
          Neos.NodeTypes.ColumnLayouts:
            - 'NodeTypes/*'
